### ISSUE TITLE
Merge caused no change, no new elements found、、、hello，I tried  you  methods，get such output

### ISSUE THREAD

**Issue by resplendent-star** [ethz-asl/voxblox-plusplus#70] opened 2020-03-29 12:20 UTC
it seems a known issue from the PCL library: PointCloudLibrary/pcl#2786

Since the issue should be fixed starting from PCL 1.10 (so far Voxblox++ was fetching PCL 1.9.1) I have merged in a PR to request PCL 1.10.1, see #68

For this to take effect on your machine you should pull the latest voxblox++ master, then wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall

It should ask something along the lines of:

$ wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall

     Change details of element (Use --merge-keep or --merge-replace to change):
  pcl_catkin

Continue: (y)es, (n)o, (v)erbosity, (a)dvanced options: 
After answering yes, run wstool update.

Else, you can just manually checkout the branch fix/advance_perception_pcl in the pcl_catkin folder.

Let me know if the issue persists.
、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、
lzw@resplendent-star:~/resplendent_code/voxblox_pp_ws/src$ wstool merge -t . voxblox-plusplus/voxblox-plusplus_https.rosinstall
Merge caused no change, no new elements found

**Comment by margaritaG** [comment] 2020-03-31 10:23
Closing as duplicate of https://github.com/ethz-asl/voxblox-plusplus/issues/66.

**Closed by margaritaG** 2020-03-31 10:23 UTC
